### PR TITLE
Bug fix for SAC-discrete.

### PR DESCRIPTION
**Pull request by ku2482**
Hi, thank you for your great work :)

I fixed some bugs related to #54 and #56.
I tested it in CartPole.py and saw the training converged more stably.

**Changes**
- [x] fix `min_qf_next_target ` to properly calculate expectations over policy.
- [x] similarly fix `policy_loss`.
- [x] fix `max_probability_action` to properly get argmax over each sample, not entire batch. (It doesn't actually affect the algorithm, though.)
- [x] fix `device` for `Replay_Memory` to train SAC-Discrete on CPU.
- [x] fix errors due to the update of PyTorch (now `torch>=1.4.0` works!!).

Thanks :)

### CODE REVIEW

**Comment by p-christ** [comment]
thanks a lot

**Comment by AlexTo** [comment]
hi @ku2482, sorry not related to these bug fixes but can you share your parameters when training with CartPole, I can't seem to get CartPole to converse :(

**Comment by ku2482** [comment]
Hi @p-christ 

Thank you for merging.
Could you close relevant issues(54, 56)??

Also, I found that this repo got older and there were a few bugs.
Can I fix bugs and clean up codes??

Thanks :)

**Comment by p-christ** [comment]
Sure will close them. Yes pls do clean up the code and do a new pull
request!

**Pull request merged**
